#
# SPDX-FileCopyrightText: 2025 Deutsche Telekom AG and others
#
# SPDX-License-Identifier: Apache-2.0
#

spring:
  application:
    name: lmos-api-server
  main:
    banner-mode: off

javaoperatorsdk:
  cache-sync-timeout: 17d
  close-client-on-stop: false
  stop-on-informer-error-during-startup: false
  check-crd-and-validate-local-model: false
  concurrent-reconciliation-threads: 60
  min-concurrent-reconciliation-threads: 22
  concurrent-workflow-executor-threads: 32
  min-concurrent-workflow-executor-threads: 12
  crd:
    apply-on-startup: true

lmos:
  router:
    embedding:
      enabled: ${EMBEDDING_ENABLED:false}
      store:
        host: ${EMBEDDING_STORE_HOST:localhost}
        port: ${EMBEDDING_STORE_PORT:6334}
        tlsEnabled: ${EMBEDDING_STORE_TLS_ENABLED:false}
        apiKey:  ${EMBEDDING_STORE_API_KEY:my-api-key}
      model:
        provider: ${EMBEDDING_MODEL_PROVIDER:openai} # Options: openai, huggingface, local_onnx
        base-url: ${EMBEDDING_MODEL_OPENAI_BASE_URL:https://api.openai.com/v1/embeddings} # Only required for provider openai
        model-name: ${EMBEDDING_MODEL_HUGGINGFACE_MODEL_NAME:intfloat/multilingual-e5-large} # Only required for provider huggingface
        api-key: ${EMBEDDING_MODEL_HUGGINGFACE_API_KEY:your-api-key} # Only required for provider huggingface
        model-path: ${EMBEDDING_MODEL_LOCAL_MODEL_PATH:/path/to/your/local/model.onnx} # Only required for provider local_onnx
        tokenizer-path: ${EMBEDDING_MODEL_LOCAL_TOKENIZER_PATH:/path/to/your/local/tokenizer.json} # Only required for provider local_onnx

logging:
  level:
    root: INFO
    org:
      springframework: WARN
      apache: WARN
    io:
      javaoperatorsdk:
        operator:
          Operator: WARN
    ai:
      ancf:
        lmos:
          operator:
            OperatorApplicationKt: WARN
    sun:
      rmi: ERROR

management:
  server:
    port: 9090
  endpoints:
    web:
      base-path: /
      exposure:
        include: prometheus,metrics,info,health
  endpoint:
    metrics:
      access: read_only
    health:
      probes:
        enabled: true
  prometheus:
    metrics:
      export:
        enabled: true
