{{- if eq .Values.embedding.enabled true }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "lmos-operator.fullname" . }}-config
data:
  EMBEDDING_ENABLED: {{ .Values.embedding.enabled | quote }}

  {{- if .Values.embedding.store.host }}
  EMBEDDING_STORE_HOST: {{ .Values.embedding.store.host | quote }}
  {{- end }}

  {{- if .Values.embedding.store.port }}
  EMBEDDING_STORE_PORT: {{ .Values.embedding.store.port | quote }}
  {{- end }}

  {{- if .Values.embedding.store.tlsEnabled }}
  EMBEDDING_STORE_TLS_ENABLED: {{ .Values.embedding.store.tlsEnabled | quote }}
  {{- end }}

  {{- if .Values.embedding.model.provider }}
  EMBEDDING_MODEL_PROVIDER: {{ .Values.embedding.model.provider | quote }}
  {{- end }}

  {{- if .Values.embedding.model.openAiUrl }}
  EMBEDDING_MODEL_OPENAI_BASE_URL: {{ .Values.embedding.model.openAiUrl | quote }}
  {{- end }}

  {{- if .Values.embedding.model.huggingfaceModelName }}
  EMBEDDING_MODEL_HUGGINGFACE_MODEL_NAME: {{ .Values.embedding.model.huggingfaceModelName | quote }}
  {{- end }}
 {{- end }}
