{{- if eq .Values.embedding.enabled true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lmos-operator.fullname" . }}-secret
  labels:
    {{- include "lmos-operator.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.embedding.store.apiKey }}
  EMBEDDING_STORE_API_KEY: {{ .Values.embedding.store.apiKey | b64enc }}
  {{- end }}
  {{- if .Values.embedding.model.huggingfaceApiKey }}
  EMBEDDING_MODEL_HUGGINGFACE_API_KEY: {{ .Values.embedding.model.huggingfaceApiKey | b64enc }}
  {{- end }}
{{- end }}